### ISSUE TITLE
causal masking

### ISSUE THREAD

**Issue by wisdom-miao** [66RING/tiny-flash-attention#2]
没有实现masking 的逻辑吗？

**Comment by 66RING** [comment]
@wisdom-miao 
是支持causal mask的，且写死了是causal模式，不支持手动传入attention mask。

causal模式支持体现在：计算时直接跳过上三角，不做计算

**Comment by wisdom-miao** [comment]
![image](https://github.com/66RING/tiny-flash-attention/assets/65605628/951e0d73-8c68-41f7-939a-e463ce3a6d34)

**Comment by wisdom-miao** [comment]
![image](https://github.com/66RING/tiny-flash-attention/assets/65605628/5bd7f808-1533-4471-8fb2-c8decbcf04d1)
是这个地方吗

**Comment by 66RING** [comment]
@wisdom-miao 是

cutlass版在这：
![image](https://github.com/66RING/tiny-flash-attention/assets/49358576/7d282e48-731b-4a99-9f58-8037b8a9022a)

**Comment by wisdom-miao** [comment]
> @wisdom-miao 是
> 
> cutlass版在这： ![image](https://private-user-images.githubusercontent.com/49358576/339604105-7d282e48-731b-4a99-9f58-8037b8a9022a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzMxODEsIm5iZiI6MTcxODMzMjg4MSwicGF0aCI6Ii80OTM1ODU3Ni8zMzk2MDQxMDUtN2QyODJlNDgtNzMxYi00YTk5LTlmNTgtODAzN2I4YTkwMjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyNDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5OWQxZjIwZDgzZGMyMmJkMTc3Y2M5OWEzMjFkZjg5Y2M1ZWRmYzczNWZmMGJlMDBiOGRkZjIxYjhjZjJlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Up6eMyK92ZMF0hqgzhZ06z5ulOPLq4v965duQDXtrCg)

嗯嗯 感谢大佬。向大佬学习的一天

**Comment by 66RING** [comment]
先关了  随时open
